apiVersion: app/v1
kind: Deployment
metadata:
  name: giropops-v2
spec:
  replicas:
  selector:
    mathLabels:
      app: giropops
  template:
    labels:
      app: giropops
      version: "2.0.0"
    annotations:
      prometheus.io/scrape: true
      promethes.io/port: "32111"
  spec:
    containers:
    - name: giropops
      image: linuxtips/nginx-promethes-exporter:2.0.0
      env:
      - name: VERSION
        value: "2.0.0"
      ports:
      - containerPort: 80
      - containerPort: 32111
