apiVersion: v1
kind: ReplicationController
metadata:
  name: myapp-rc
    app: myapp
    type: frontend
spec:
  template:
    #(aqui nos colocamos o pod definition, porem sem o kind )
    metadata:
      name: myapp-pod
      labels:
        app: myapp
        type: frontend
    spec:
      containers:
      - name: nginx-container
        image: nginx
  replicas: 3
  