apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jekyll-site
  namespace: development
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: Pod
metadata:
  name: jekyll
  namespace: development
  labels:
    run: jekyll
spec:
  volumes:
  - name: site
    persistentVolumeClaim:
      claimName: jekyll-site

  initContainers:
  - name: copy-jekyll-site
    image: kodekloud/jekyll
    command: ["jekyll", "new", "/site" ] 
    volumeMounts:
    - name: site
      mountPath: "/site"

  containers:
  - name: jekyll
    image: kodekloud/jekyll-serve
    volumeMounts:
    - name: site
      mountPath: "/site"
---
apiVersion: v1
kind: Service
metadata:
  name: jekyll
  namespace: development
  labels:
    run: jekyll
spec:
  type: NodePort
  selector:
    run: jekyll 
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 4000
      nodePort: 30097

