apiVersion: v1
kind: Service
metadata:
  name: drupal-service
  labels:
    app: drupal
spec:
  type: NodePort
  selector:
    app: drupal
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30095
controlplane $ cat drupal-deploy.yaml 
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: drupal
  name: drupal
spec:
  replicas: 1
  selector:
    matchLabels:
      app: drupal
  template:
    metadata:
      labels:
        app: drupal
    spec:
      volumes:
      - name: vol-drupal
        persistentVolumeClaim:
          claimName: drupal-pvc
      initContainers:
      - name: init-sites-volume
        image: drupal:8.6
        volumeMounts:
        - name: vol-drupal
          mountPath: /data
        command: [ "/bin/bash", "-c" ]
        args: [ 'cp -r /var/www/html/sites/ /data/; chown www-data:www-data /data/ -R' ]
      containers:
      - name: drupal
        image: drupal:8.6
        volumeMounts:
        - name: vol-drupal
          mountPath: /var/www/html/modules
          subPath: modules
        - name: vol-drupal
          mountPath: /var/www/html/profiles
          subPath: profiles
        - name: vol-drupal
          mountPath: /var/www/html/sites
          subPath: sites
        - name: vol-drupal
          mountPath: /var/www/html/themes
          subPath: themes