apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: drupal-mysql
  name: drupal-mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: drupal-mysql
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: drupal-mysql
    spec:
      volumes:
      - name: vol-drupal
        persistentVolumeClaim:
          claimName: drupal-mysql-pvc
      #- name: sec-mysql
      #  secret:
      #    secretName: drupal-mysql-secret
      containers:
      - image: mysql:5.7
        name: mysql
        volumeMounts:
        - name: vol-drupal
          mountPath: /var/lib/mysql
          subPath: dbdata
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: drupal-mysql-secret
              key: MYSQL_ROOT_PASSWORD
        - name: MYSQL_DATABASE
          valueFrom:
            secretKeyRef:
              name: drupal-mysql-secret
              key: MYSQL_DATABASE
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: drupal-mysql-secret
              key: MYSQL_USER